use essay_plot::{api::{renderer::{Renderer, Result}, Point, TextStyle}, artist::PathStyle};


#[derive(Clone, Copy, Debug)]
pub enum Emoji {
    AlarmClock,
    AnatomicalHeart,
    Bacon,
    BalanceScale,
    Banana,
    Bandage,
    Beans,
    Bell,
    Broccoli,
    Butterfly,
    BowAndArrow,
    Candle,
    Candy,
    Carrot,
    CheckMark,
    Cheese,
    CrossMark,
    Coffee,
    Compass,
    CookedRice,
    Cupcake,
    Crab,
    Detective,
    DirectHit,
    Dog,
    DoubleExclamationMark,
    Droplet,
    EmptyNest,
    ExclamationQuestionMark,
    Eyeglasses,
    Eyes,

    FaceAnxious,
    FaceAstonished,
    FaceConfounded,
    FaceCowboy,
    FaceDelicious,
    FaceDisappointed,
    FaceFearful,
    FaceFearScream,
    FaceFreezing,
    FaceFrowning,
    FaceGrimacing,
    FaceGrinning,
    FaceOpenMouth,
    FaceOverheated,
    FaceMonocle,
    FaceNauseated,
    FaceNeutral,
    FaceShaking,
    FaceSleeping,
    FaceSleepy,
    FaceSlightlySmiling,
    FaceSunglasses,
    FaceUpsideDown,
    FaceThinking,
    FaceVomiting,
    FaceWinking,
    FaceWithCowboyHat,
    FaceWithThermometer,
    FaceWorried,
    FaceYawning,

    Farmer,
    Fire,
    Flashlight,
    Footprints,
    FourLeafClover,
    ForkAndKnife,
    HighVoltage,
    Honeybee,
    House,
    Hamburger,
    Infinity,
    Lemon,
    LightBulb,
    Lollipop,
    Lungs,
    MagnifyingGlassLeft,
    MagnifyingGlassRight,
    ManJuggling,
    ManRunning,
    ManShrugging,
    NoEntry,
    OctagonalSign,
    Onion,
    PartyPopper,
    Pedestrian,
    Pig,
    Prohibited,
    Radioactive,
    Ribbon,
    RightArrowCurvingLeft,
    Salt,
    Shark,
    Sleeping,
    StopSign,
    Sushi,
    Telescope,
    Trophy,
    Warning,
    Whale,

    // buttons
    CheckMarkButton,
    CrossMarkButton,
    FastForwardButton,
    FastReverseButton,
    PlayButton,
    PlayOrPauseButton,
    PauseButton,
    ReverseButton,
    StopButton,
}

impl Emoji {
    fn _new() -> Self {
        Self::Footprints
    }

    pub fn code(&self) -> &str {
        match self {
            Emoji::AlarmClock => "\u{23f0}",
            Emoji::AnatomicalHeart => "\u{1fac0}",
            Emoji::Bacon => "\u{1f953}",
            Emoji::BalanceScale => "\u{2696}",
            Emoji::Bandage => "\u{1fa79}",
            Emoji::Banana => "\u{1f34c}",
            Emoji::Bell => "\u{1f514}",
            Emoji::Beans => "\u{1fad8}",
            Emoji::BowAndArrow => "\u{1f3f9}",
            Emoji::Broccoli => "\u{1f966}",
            Emoji::Butterfly => "\u{1f98b}",
            Emoji::Candle => "\u{1f56f}",
            Emoji::Candy => "\u{1f36c}",
            Emoji::Carrot => "\u{1f955}",
            Emoji::Cheese => "\u{1f9c0}",
            Emoji::CheckMark => "\u{2714}",
            Emoji::Coffee => "\u{2615}",
            Emoji::Compass => "\u{1f9ed}",
            Emoji::CookedRice => "\u{1f35a}",
            Emoji::Crab => "\u{1f980}",
            Emoji::CrossMark => "\u{274c}",
            Emoji::Cupcake => "\u{1f9c1}",
            Emoji::Detective => "\u{1f575}",
            Emoji::DirectHit => "\u{1f3af}",
            Emoji::Dog => "\u{1f415}",
            Emoji::DoubleExclamationMark => "\u{203c}",
            Emoji::Droplet => "\u{1f4a7}",
            Emoji::EmptyNest => "\u{1fab9}",
            Emoji::ExclamationQuestionMark => "\u{2049}",
            Emoji::Eyeglasses => "\u{1f453}",
            Emoji::Eyes => "\u{1f440}",

            Emoji::FaceAnxious => "\u{1f630}",
            Emoji::FaceAstonished => "\u{1f632}",
            Emoji::FaceConfounded => "\u{1f616}",
            Emoji::FaceCowboy => "\u{1f920}",
            Emoji::FaceDelicious => "\u{1f60b}",
            Emoji::FaceDisappointed => "\u{1f61e}",
            Emoji::FaceFearful => "\u{1f628}",
            Emoji::FaceFearScream => "\u{1f631}",
            Emoji::FaceFreezing => "\u{1f976}",
            Emoji::FaceFrowning => "\u{2639}",
            Emoji::FaceGrimacing => "\u{1f62c}",
            Emoji::FaceGrinning => "\u{1f600}",
            Emoji::FaceMonocle => "\u{1f9d0}",
            Emoji::FaceNauseated => "\u{1f922}",
            Emoji::FaceNeutral => "\u{1f610}",
            Emoji::FaceOverheated => "\u{1f975}",
            Emoji::FaceOpenMouth => "\u{1f62e}",
            Emoji::FaceShaking => "\u{1fae8}",
            Emoji::FaceSleepy => "\u{1f62a}",
            Emoji::FaceSleeping => "\u{1f634}",
            Emoji::FaceSlightlySmiling => "\u{1f642}",
            Emoji::FaceSunglasses => "\u{1f60e}",
            Emoji::FaceThinking => "\u{1f914}",
            Emoji::FaceUpsideDown => "\u{1f643}",
            Emoji::FaceVomiting => "\u{1f92e}",
            Emoji::FaceWinking => "\u{1f609}",
            Emoji::FaceWithCowboyHat => "\u{1f920}",
            Emoji::FaceWithThermometer => "\u{1f912}",
            Emoji::FaceWorried => "\u{1f61f}",
            Emoji::FaceYawning => "\u{1f971}",

            Emoji::Farmer => "\u{1f9d1}",
            Emoji::Fire => "\u{1f525}",
            Emoji::Flashlight => "\u{1f526}",
            Emoji::Footprints => "\u{1f463}",
            Emoji::FourLeafClover => "\u{1f340}",
            Emoji::ForkAndKnife => "\u{1f374}",
            Emoji::Hamburger => "\u{1f354}",
            Emoji::HighVoltage => "\u{26a1}",
            Emoji::Honeybee => "\u{1f41d}",
            Emoji::House => "\u{1f3e0}",
            Emoji::Infinity => "\u{267e}",
            Emoji::Lemon => "\u{1f34b}",
            Emoji::LightBulb => "\u{1f4a1}",
            Emoji::Lollipop => "\u{1f36d}",
            Emoji::Lungs => "\u{1fac1}",
            Emoji::MagnifyingGlassLeft => "\u{1f50d}",
            Emoji::MagnifyingGlassRight => "\u{1f50e}",
            Emoji::ManJuggling => "\u{1f939}",
            Emoji::ManRunning => "\u{1f3c3}",
            Emoji::ManShrugging => "\u{1f937}",
            Emoji::NoEntry => "\u{26d4}",
            Emoji::OctagonalSign => "\u{1f6d1}",
            Emoji::Onion => "\u{1f9c5}",
            Emoji::PartyPopper => "\u{1f389}",
            Emoji::Pig => "\u{1f416}",
            Emoji::Pedestrian => "\u{1f6b6}",
            Emoji::Prohibited => "\u{1f6ab}",
            Emoji::Radioactive => "\u{2622}",
            Emoji::Ribbon => "\u{1f380}",
            Emoji::RightArrowCurvingLeft => "\u{21a9}", // u-turn
            Emoji::Salt => "\u{1f9c2}",
            Emoji::Shark => "\u{1f988}",
            Emoji::Sleeping => "\u{1f4a4}",
            Emoji::StopSign => "\u{1f6d1}",
            Emoji::Sushi => "\u{1f363}",
            Emoji::Telescope => "\u{1f52d}",
            Emoji::Trophy => "\u{1f3c6}",
            Emoji::Warning => "\u{26a0}",
            Emoji::Whale => "\u{1f40b}",

            // buttons
            Emoji::CheckMarkButton => "\u{2705}",
            Emoji::CrossMarkButton => "\u{274e}",
            Emoji::FastForwardButton => "\u{23e9}",
            Emoji::FastReverseButton => "\u{23ea}",
            Emoji::PlayButton => "\u{25b6}",
            Emoji::PlayOrPauseButton => "\u{23ef}",
            Emoji::PauseButton => "\u{23f8}",
            Emoji::ReverseButton => "\u{25c0}",
            Emoji::StopButton => "\u{23f9}",
        }
    }
}

pub trait SymbolDraw {
    fn draw(
        &self, 
        ui: &mut dyn Renderer, 
        pos: Point, 
        style: &PathStyle,
        text_style: &mut TextStyle
    ) -> Result<()>;
}

impl SymbolDraw for Emoji {
    fn draw(
        &self, 
        ui: &mut dyn Renderer, 
        pos: Point, 
        style: &PathStyle,
        text_style: &mut TextStyle
    ) -> Result<()> {
        ui.draw_text(pos, self.code(), 0., style, text_style)
    }
}
