[package]
name = "test-log"
version = "0.0.0"
edition = "2021"

[dependencies]
log = { version = "0.4.17" }

essay-ecs = { path = "../../../essay-ecs" }
#essay-ecs = { git = "https://github.com/ferg-essay/essay-ecs", version="0.1.13" }

[lib]
doctest = false