[package]
name = "ui-graphics"
version = "0.0.0"
edition = "2021"

[dependencies]
log = { version = "0.4.17" }
env_logger = { version = "0.10.0" }
#winit = "0.28"
#wgpu = "0.15"
#sdl2 = "0.35"
egui = "0.22"
eframe = "0.22"


# workspace dependencies
#ticker.workspace = true
#ticker = { path = "../ticker" }
#ticker = {version = "0.1.9"}

[lib]
doctest = false

